# Generated by Django 4.2.23 on 2025-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
